name: Tech Challenge QA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# cancel outdated jobs
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  api-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            api/package-lock.json
            client/package-lock.json

      - run: npm ci --prefer-offline
      - run: npm run test

      - name: Upload API tests results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: api-test-results
          path: api/test_results

  ui-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/base:14.19.0
      options: --user 1001
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            api/package-lock.json
            client/package-lock.json

      - name: Restore Cypress Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}

      - run: npm ci --prefer-offline

      - name: Run Cypress tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm --prefix api start, npm --prefix client start
          wait-on: "http://localhost:3000"
          command: npm --prefix client run cypress:run

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-results
          path: |
            client/cypress/screenshots
            client/cypress/videos

      - name: Upload UI tests results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ui-test-results
          path: ui/test_results

  publish-test-results:
    needs: [api-test, ui-test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish tests results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
          check_name: "Tests Results"
